name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare files for GitHub Pages
        run: |
          mkdir public
          cp calendar.html public/index.html
          cp calendar.js public/

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload files to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Publish GitHub Pages
        uses: actions/deploy-pages@v1
